### ISSUE TITLE
Race condition in the GetChangedEntries method

### ISSUE THREAD

**Issue by hankovich** [JValck/Ramses#1]
Hi, I found a bug [in the GetChangedEntries method](https://github.com/JValck/Ramses/blob/master/Ramses/LifecycleDbContext.cs#L85)

This code has a race condition.

```
var entries = base.ChangeTracker.Entries();
var clone = new List<Entity>(entries.Count());
Parallel.ForEach(entries, (entry) =>
{
    clone.Add(...); <- here
});
```

`List<T>`'s `Add` method is not thread-safe, so there's no guarantee that all `entries`'s elements will be copied to `clone`.
To fix the issue `Parallel.ForEach` should be changed to a boring `foreach`.

**Comment by JValck** [comment]
Thanks for pointing out @hankovich !
I used the `Parallel.ForEach` for performance considerations, but forgot that the `Add` method is not thread-safe.
I'll fix this asap.
